chore: update husky

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,4 +1,13 @@
 #!/usr/bin/env sh
 . "$(dirname -- "$0")/_/husky.sh"
 
+if git config --get alias.internal-check > /dev/null 2>&1; then
+    git internal-check
+
+    if [ $? -ne 0 ]; then
+        echo "Internal check failed"
+        exit 1
+    fi
+fi
+
 npx lint-staged
